### ISSUE TITLE
Does anyone else get TTransportException with hbase 1.2.0  happybase 1.2.0 thriftpy2 0.4.5

### ISSUE THREAD

**Issue by HITxuefeng** [python-happybase/happybase#226]
my version is :
hbase    1.2.0
happybase  1.2.0
thriftpy2   0.4.5 

`def get_tables_name(host,port):
    conn = happybase.Connection(host=host,port=port,protocol='compact',transport='framed')
    return conn.tables()`

but has error like this:
`DEBUG:happybase.connection:Opening Thrift transport to 172.16.18.201:9090
Traceback (most recent call last):
  File "/Users/xuefeng/projects/facerecognition/facerecognition/storage.py", line 56, in <module>
    get_tables_name("172.16.18.201",9090)
  File "/Users/xuefeng/projects/facerecognition/facerecognition/storage.py", line 47, in get_tables_name
    return conn.tables()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/happybase/connection.py", line 242, in tables
    names = self.client.getTableNames()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/thrift.py", line 203, in _req
    return self._recv(_api)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/thrift.py", line 215, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/protocol/compact.py", line 143, in read_message_begin
    proto_id = self.read_ubyte()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/protocol/compact.py", line 218, in read_ubyte
    result, = unpack('!B', self.trans.read(1))
  File "thriftpy2/transport/framed/cyframed.pyx", line 100, in thriftpy2.transport.framed.cyframed.TCyFramedTransport.read
  File "thriftpy2/transport/cybase.pyx", line 137, in thriftpy2.transport.cybase.CyTransportBase.get_string
  File "thriftpy2/transport/framed/cyframed.pyx", line 48, in thriftpy2.transport.framed.cyframed.TCyFramedTransport.c_read
  File "thriftpy2/transport/framed/cyframed.pyx", line 68, in thriftpy2.transport.framed.cyframed.TCyFramedTransport.read_frame
  File "thriftpy2/transport/framed/cyframed.pyx", line 31, in thriftpy2.transport.framed.cyframed.TCyFramedTransport.read_trans
  File "thriftpy2/transport/cybase.pyx", line 61, in thriftpy2.transport.cybase.TCyBuffer.read_trans
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thriftpy2/transport/socket.py", line 132, in read
    message='TSocket read 0 bytes')
thriftpy2.transport.TTransportException: TTransportException(type=4, message='TSocket read 0 bytes')
DEBUG:happybase.connection:Closing Thrift transport to 172.16.18.201:9090`

anyone resolved it ? i need some help .thank you.

**Comment by xt84** [comment]
https://github.com/python-happybase/happybase/issues/130 you can found solution here 
or here
https://www.programmersought.com/article/73001435144/
