### ISSUE TITLE
org.apache.hadoop.hbase.NamespaceNotFoundException: 

### ISSUE THREAD

**Issue by appleyuchi** [python-happybase/happybase#242]
>>> import happybase

>>> connection = happybase.Connection(host="Desktop", port=9090)
>>> connection.open()
>>> families = {"base":dict(),"address":dict()}
>>> connection.create_table('databasename:tablename',families)

Hbase_thrift.IOError: IOError(message=b'org.apache.hadoop.hbase.NamespaceNotFoundException: org.apache.hadoop.hbase.NamespaceNotFoundException: databasename\n\t
	at org.apache.hadoop.hbase.master.ClusterSchemaServiceImpl.getNamespace(ClusterSchemaServiceImpl.java:119)\n\t
	at org.apache.hadoop.hbase.master.HMaster.createTable(HMaster.java:2034)\n\t
	at org.apache.hadoop.hbase.master.MasterRpcServices.createTable(MasterRpcServices.java:659)\n\t
	at org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)\n\t
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:413)\n\t
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)\n\t
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)\n\t
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)\n\n\t
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\t
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\t
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\t
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\t
	at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException.instantiateException(RemoteWithExtrasException.java:99)\n\t
	at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException.unwrapRemoteException(RemoteWithExtrasException.java:89)\n\t
	at org.apache.hadoop.hbase.shaded.protobuf.ProtobufUtil.makeIOExceptionOfException(ProtobufUtil.java:364)\n\t
	at org.apache.hadoop.hbase.shaded.protobuf.ProtobufUtil.handleRemoteException(ProtobufUtil.java:352)\n\t
	at org.apache.hadoop.hbase.client.MasterCallable.call(MasterCallable.java:101)\n\t
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)\n\t
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3133)\n\t
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3125)\n\t
	at org.apache.hadoop.hbase.client.HBaseAdmin.createTableAsync(HBaseAdmin.java:669)\n\t
	at org.apache.hadoop.hbase.client.HBaseAdmin.createTable(HBaseAdmin.java:642)\n\t
	at org.apache.hadoop.hbase.client.HBaseAdmin.createTable(HBaseAdmin.java:617)\n\t
	at org.apache.hadoop.hbase.thrift.ThriftHBaseServiceHandler.createTable(ThriftHBaseServiceHandler.java:619)\n\t
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\t
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\t
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\t
	at java.lang.reflect.Method.invoke(Method.java:498)\n\t
	at org.apache.hadoop.hbase.thrift.HbaseHandlerMetricsProxy.invoke(HbaseHandlerMetricsProxy.java:72)\n\t
	at com.sun.proxy.$Proxy12.createTable(Unknown Source)\n\t
	at org.apache.hadoop.hbase.thrift.generated.Hbase$Processor$createTable.getResult(Hbase.java:3958)\n\t
	at org.apache.hadoop.hbase.thrift.generated.Hbase$Processor$createTable.getResult(Hbase.java:3937)\n\t
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)\n\t
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)\n\t
	at org.apache.hadoop.hbase.thrift.TBoundedThreadPoolServer$ClientConnnection.run(TBoundedThreadPoolServer.java:293)\n\t
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\
 java.lang.Thread.run(Thread.java:748)\n
 Caused by: org.apache.hadoop.hbase.ipc.RemoteWithExtrasException(org.apache.hadoop.hbase.NamespaceNotFoundException): org.apache.hadoop.hbase.NamespaceNotFoundException: databasename\n\
 org.apache.hadoop.hbase.master.ClusterSchemaServiceImpl.getNamespace(ClusterSchemaServiceImpl.java:119)\n\
 org.apache.hadoop.hbase.master.HMaster.createTable(HMaster.java:2034)\n\
 org.apache.hadoop.hbase.master.MasterRpcServices.createTable(MasterRpcServices.java:659)\n\
 org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)\n\
 org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:413)\n\
 org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)\n\
 org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)\n\
 org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)\n\n\
 org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:389)\n\
 org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:97)\n\
 org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:423)\n\
 org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:419)\n\
 org.apache.hadoop.hbase.ipc.Call.callComplete(Call.java:117)\n\
 org.apache.hadoop.hbase.ipc.Call.setException(Call.java:132)\n\
 org.apache.hadoop.hbase.ipc.NettyRpcDuplexHandler.readResponse(NettyRpcDuplexHandler.java:162)\n\
 org.apache.hadoop.hbase.ipc.NettyRpcDuplexHandler.channelRead(NettyRpcDuplexHandler.java:192)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)\n\
 org.apache.hbase.thirdparty.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)\n\
 org.apache.hbase.thirdparty.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)\n\
 org.apache.hbase.thirdparty.io.netty.handler.timeout.IdleS
eHandler.channelRead(IdleS
eHandler.java:286)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)\n\
 org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)\n\
 org.apache.hbase.thirdparty.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)\n\
 org.apache.hbase.thirdparty.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)\n\
 org.apache.hbase.thirdparty.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\
 org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)\n\
 org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)\n\
 org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)\n\
 org.apache.hbase.thirdparty.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)\n\
 org.apache.hbase.thirdparty.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)\n\
 org.apache.hbase.thirdparty.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\n')
>>> 

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
please help,thanks~

**Comment by wbolster** [comment]
looks like you're hitting a hbase error, not a happybase one. you could try a name without colons, or ensure your hbase is setup properly.

closing this since this is the happybase bug tracker, and this seems not the case here.

http://hbase.apache.org/apidocs/org/apache/hadoop/hbase/NamespaceNotFoundException.html

**Comment by appleyuchi** [comment]
@wbolster could you tell me how did you run these python codes when no jars added?
My Hbase is OK when execute commands in `hbase shell`

**Comment by wbolster** [comment]
what do you mean, no jars added? this is a python library, not a java project?

**Comment by wbolster** [comment]
so this is solved? it would be appreciated if you would leave a comment, @appleyuchi
