### ISSUE TITLE
TypeError: __str__ returned non-string (type bytes) hbase

### ISSUE THREAD

**Issue by zxtanzxzx** [python-happybase/happybase#248]
i am trying to connect my Hbase server to retreive some rows. 
When run, the TypeError: __str__ returned non-string (type bytes) hbase returned.

Code Snippet
```
import happybase
connection = happybase.Connection('hbase-server', 
                                  port=9090,
                                  timeout=None,
                                  autoconnect=True,
                                  protocol='binary',transport='buffered')
table = connection.table('example')
row = table.row(b'row1234')
print(table)
```

Traceback 
```
---------------------------------------------------------------------------
TApplicationException                     Traceback (most recent call last)
    [... skipping hidden 1 frame]

<ipython-input-35-5e971b952ad1> in <module>
      7 table = connection.table('example')
----> 8 table.row('row2009')
      9 print(table)

~/venv/lib/python3.6/site-packages/happybase/table.py in row(self, row, columns, timestamp, include_timestamp)
    121             rows = self.connection.client.getRowWithColumns(
--> 122                 self.name, row, columns, {})
    123         else:

~/venv/lib/python3.6/site-packages/thriftpy2/thrift.py in _req(self, _api, *args, **kwargs)
    218         if not getattr(result_cls, "oneway"):
--> 219             return self._recv(_api)
    220 

~/venv/lib/python3.6/site-packages/thriftpy2/thrift.py in _recv(self, _api)
    235             self._iprot.read_message_end()
--> 236             raise x
    237         result = getattr(self._service, _api + "_result")()

<class 'str'>: (<class 'TypeError'>, TypeError('__str__ returned non-string (type bytes)',))

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2047                                             value, tb, tb_offset=tb_offset)
   2048 
-> 2049                     self._showtraceback(etype, value, stb)
   2050                     if self.call_pdb:
   2051                         # drop into debugger

~/venv/lib/python3.6/site-packages/ipykernel/zmqshell.py in _showtraceback(self, etype, evalue, stb)
    547             'traceback' : stb,
    548             'ename' : str(etype.__name__),
--> 549             'evalue' : py3compat.safe_unicode(evalue),
    550         }
    551 

~/venv/lib/python3.6/site-packages/ipython_genutils/py3compat.py in safe_unicode(e)
     63     """
     64     try:
---> 65         return unicode_type(e)
     66     except UnicodeError:
     67         pass

TypeError: __str__ returned non-string (type bytes)
```

**Comment by wbolster** [comment]
ah, this seems to be a `Table.__repr__` problem indeed.

you probably wanted to do `print(row)` though, not `print(table)`.

**Comment by wbolster** [comment]
on second look, this may be something in `thriftpy` or even in `ipython`.

can you try with a plain `python` shell, and post the (shorter) traceback?

**Comment by zxtanzxzx** [comment]
Hbase version is 2.1.1

This is the output
```
Traceback (most recent call last):
  File "python-example/happyB.py", line 8, in <module>
    row = table.row(b'row1234')
  File "/home/zx/hbase/huawei-demo-client/happyB/lib/python3.8/site-packages/happybase/table.py", line 121, in row
    rows = self.connection.client.getRowWithColumns(
  File "/home/zx/hbase/huawei-demo-client/happyB/lib/python3.8/site-packages/thriftpy2/thrift.py", line 219, in _req
    return self._recv(_api)
  File "/home/zx/hbase/huawei-demo-client/happyB/lib/python3.8/site-packages/thriftpy2/thrift.py", line 236, in _recv
    raise x
thriftpy2.thrift.TApplicationException: <exception str() failed>
```

**Comment by zxtanzxzx** [comment]
@wbolster Do you know how to check thrift version?  I can't figure out wher an dhow to check
I am thinking this maybe the same issue in <https://github.com/Thriftpy/thriftpy2/issues/79> 
Since i am using Huawei Cloud MapReduce service.

**Comment by zxtanzxzx** [comment]
From happybase todo at <https://happybase.readthedocs.io/en/latest/todo.html>
One of the item is
```
Port HappyBase over to the (still experimental) HBase Thrift2 API when it becomes mainstream, and expose more of the underlying features nicely in the HappyBase API.
```

Since I am running Thrift2Server. This maybe the cause of the error. @wbolster Any comment?

**Comment by zxtanzxzx** [comment]
After some digging, the service i am using was running on thrift 2 server. I ran Thrift 1 and it all works just fine :)
